CREATE DATABASE GOFFLE_DB;

USE GOFFLE_DB;


CREATE USER 'suihin'@'%' IDENTIFIED BY 'tq3718';

GRANT ALL PRIVILEGES ON GOFFLE_DB.* TO 'suihin'@'%';

FLUSH PRIVILEGES;



CREATE TABLE USERS (
	ID						BIGINT					NOT NULL AUTO_INCREMENT COMMENT '사용자번호',
	LOGIN_ID				VARCHAR(20)				NOT NULL COMMENT '로그인 아이디',
	PASSWORD				VARCHAR(255)			NOT NULL COMMENT '로그인 비밀번호',
	NAME					VARCHAR(12)				NOT NULL COMMENT '사용자 이름',
	EMAIL					VARCHAR(40)				NOT NULL COMMENT '이메일',
	LOGIN_TYPE				VARCHAR(5)				NOT NULL COMMENT '로그인 유형',
	ENABLED_AT				TINYINT(1)				NOT NULL COMMENT '계정 활성화',
	USE_YN					CHAR(1)					NOT NULL DEFAULT 'Y' COMMENT '사용여부',
	DELETE_YN				CHAR(1)					NOT NULL DEFAULT 'N' COMMENT '삭제 여부',
	CREATED_DATETIME		DATETIME				NOT NULL DEFAULT NOW() COMMENT '가입 일자',
	UPDATED_DATETIME		DATETIME				NOT NULL COMMENT '정보 변경일자',
	PRIMARY KEY (ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '사용자계정테이블';



CREATE TABLE USER_ROLES (
	USER_ROLE_ID			BIGINT					NOT NULL AUTO_INCREMENT COMMENT '사용자권한번호',
	USER_ID					BIGINT					NOT NULL COMMENT '사용자번호',
	ROLE					VARCHAR(15)				NOT NULL COMMENT '권한코드 (ROLE_USER/ROLE_ADMIN)',
	USE_YN					CHAR(1)					NOT NULL DEFAULT 'Y' COMMENT '권한사용여부',
	CREATED_DATETIME		DATETIME				NOT NULL DEFAULT NOW() COMMENT '권한등록일자',
	UPDATED_DATETIME		DATETIME				NOT NULL COMMENT '권한변경일자',
	PRIMARY KEY (USER_ROLE_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '사용자별권한테이블';



CREATE TABLE LOGIN_HISTORY (
	LOGIN_HISTORY_ID		BIGINT					NOT NULL AUTO_INCREMENT COMMENT '로그인이력번호',
	USER_ID					BIGINT					NOT NULL COMMENT '사용자번호',
	CLIENT_IP				VARCHAR(255)			NOT NULL COMMENT '접속 IP',
	USER_AGENT				VARCHAR(255)			NOT NULL COMMENT '접속 USER-AGENT',
	LOGIN_DATETIME			DATETIME				NOT NULL COMMENT '로그인 일자',
	PRIMARY KEY (LOGIN_HISTORY_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '로그인이력테이블';



CREATE TABLE USER_PROFILES (
	USER_PROFILE_ID			BIGINT					NOT NULL AUTO_INCREMENT COMMENT '사용자프로필번호',
	USER_ID					BIGINT					NOT NULL COMMENT '사용자번호',
	PROFILE_IMAGE_PATH		VARCHAR(255)			NOT NULL DEFAULT 'NONE' COMMENT '프로필이미지 파일저장경로',
	PROFILE_IMAGE_NAME		VARCHAR(200)			NOT NULL DEFAULT 'NONE' COMMENT '프로필이미지 파일명',
	PROFILE_IMAGE_SIZE		BIGINT					NOT NULL DEFAULT 0 COMMENT '프로필이미지 크기',
	UNIV					VARCHAR(50)				NOT NULL DEFAULT 'NONE' COMMENT '출신 대학교명',
	CITY					VARCHAR(25)				NOT NULL DEFAULT 'NONE' COMMENT '거주 중인 도시명',
	CREATED_DATETIME		DATETIME				NOT NULL DEFAULT NOW() COMMENT '프로필 등록일자',
	UPDATED_DATETIME		DATETIME				NOT NULL COMMENT '프로필변경일자',
	PRIMARY KEY (USER_PROFILE_ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '사용자프로필테이블';



CREATE TABLE TEAMS (
	TEAM_ID					BIGINT					NOT NULL AUTO_INCREMENT COMMENT '팀번호',
	TEAM_NAME				VARCHAR(100)			NOT NULL COMMENT '팀명',
	INTRODUCTION			VARCHAR(150)			NOT NULL COMMENT '팀소개글(50자이내)',
	CREATED_DATETIME		DATETIME				NOT NULL DEFAULT NOW() COMMENT '팀정보 등록일자',
	UPDATED_DATETIME		DATETIME				NOT NULL COMMENT '팀정보 변경일자',
	USE_YN					CHAR(1)					NOT NULL DEFAULT 'Y' COMMENT '사용여부',
	DELETE_YN				CHAR(1)					NOT NULL DEFAULT 'N' COMMENT '팀정보 삭제여부',
	PRIMARY KEY (TEAM_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '팀정보테이블';



CREATE TABLE TEAM_USERS (
	TEAM_ID					BIGINT					NOT NULL COMMENT '팀번호',
	USER_ID					BIGINT					NOT NULL COMMENT '사용자번호',
	IS_CAPTAIN				CHAR(1)					NOT NULL COMMENT '팀장여부',
	CREATED_DATETIME		DATETIME				NOT NULL DEFAULT NOW() COMMENT '팀원등록일자',
	UPDATED_DATETIME		DATETIME				NOT NULL COMMENT '팀원변경일자',
	FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (TEAM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '팀원테이블';


