#
# 스프링부트 애플리케이션 공통 환경 설정
#


spring:
  config:
    activate:
      on-profile:
        - common
  application:
    name: goffle-v.1.0
  main:
    # 서버 런타임되면 콘솔창에 출려되는 배너를 끈다.
    banner-mode: OFF
  # 웹 브라우저의 새로고침을 통한 변경된 화면의 적용을 위한 `타임리프`와 `정적 리소스`의 경로와 캐시값을 설정한다.
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    enabled: true
    cache: false  # 개발이 완료되면 `true`로 변경
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
      cache:
        period: 36000

# 서버 설정 : 포트 번호 변경과 HTTP 요청 및 응답의 인코딩 설정
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 마이바티스 설정
mybatis:
  # 서버 구동시 마이바티스의 동작 제어를 위한 설정 = mybatis-config.xml의 <setting></setting>
  configuration:
    # 매퍼의 네임스페이스 단위로 동작되는 캐시를 비활성화
    cache-enabled: false
    # 지연 로딩 비활성화
    lazy-loading-enabled: false
    # SQL 세션 객체마다 가지고 있는 로컬 캐시의 적용 범위를 설정
    local-cache-scope: STATEMENT
    # 스네이크 표기법의 컬럼명 → 카멜 케이스 표기법으로 변경
    map-underscore-to-camel-case: true
    # 조회된 값이 NULL일 경우, 누락될 수 있는 문제를 방지하기 위해 setter()와 put()를 호출
    call-setters-on-nulls: true
    # 마이바티스에서 NULL값인 파라미터 처리
    jdbc-type-for-null: NULL
  # 사용자 정의 타입 핸들러의 패키지 경로를 지정
  type-handlers-package: com.tnbin.goffle.global.common.mybatis
  # 클래스 타입의 매핑을 위한 클래스명 작성시 패키지 생략을 위한 설정
  type-aliases-package: com.tnbin.goffle.domain.**.dto
  mapper-locations:
    - classpath:mapper/*_mapper.xml

# 로깅 레벨 설정
logging:
  level:
    web: debug
    root: info